### ISSUE TITLE
Question: How to override templates

### ISSUE THREAD

**Issue by rolandschuetz** [KaufmannDigital/CleverReach#1]
Thanks for the package. I'm currently trying it out. Is there a way to override templates with custom ones for different styling?

**Comment by Nikdro** [comment]
Hi @rolandschuetz!

Sure, you can easily override the Template as described here: http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/ModelViewController.html#configuring-views-through-views-yaml

That should be the way to go (untested): 
```
-
  requestFilter: 'isPackage("KaufmannDigital.CleverReach") && isController("Subscription") && isAction("index")'
  options:
    templatePathAndFilename: 'resource://My.Package/Private/Templates/....html'
```

If you have any further questions or suggestions for improvements, please don't hesitate to coact me. Just here or in Neos-Slack (@ndroste)
